"""empty message

Revision ID: 38ecf0673619
Revises: a3c1fbd5c29f
Create Date: 2022-06-06 22:29:56.463743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ecf0673619'
down_revision = 'a3c1fbd5c29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'address')
    # ### end Alembic commands ###
